### PR TITLE
Fix spacing issues with StaticBadge on mobile

### LINKED ISSUE #61: Issue with StaticBadge image clipping into footer
Screenshot 2024-06-29 at 10 03 07 PM

Thanks Success!

### PR DESCRIPTION
**Pull request by Radicitus**
Closes #61

### CODE REVIEW

File: app/page.tsx [hunk 1]
```diff
@@ -1,13 +1,21 @@
...
 
 export const revalidate = 1200;
 
 export default function Home() {
   return (
-    <main className="flex h-screen w-full justify-center">
-      {isMobileDevice() ? <StaticBadge /> : <DynamicBadge />}
-    </main>
+    <>
+      {isMobileDevice() ? (
```
Comment (Radicitus) [inline app/page.tsx:10]: Need to check if this is reliable. It doesn't seem to work well on dev tools in chrome when passing media queries.

Comment (Radicitus) [reply app/page.tsx:10]: Will check this later. I'm lazy lol
