### PR TITLE
Migrate to Single Page Web App with smooth scroll and fix render bug on badge hover

### LINKED ISSUE #65: Fix stutter when hovering over badge

### PR DESCRIPTION
**Pull request by Radicitus**
Closes #65 

Thanks Aubrey!

### CODE REVIEW

File: app/page.tsx [hunk 1]
```diff
@@ -1,21 +1,25 @@
...
+import Projects from "@/components/Projects";
 
 export const revalidate = 1200;
 
 export default function Home() {
   return (
     <>
       {isMobileDevice() ? (
-        <main className="flex w-full justify-center">
+        <main id="home" className="flex w-full justify-center">
```
Comment (Radicitus) [inline app/page.tsx:13]: Can this be set to / or something else?

Comment (Radicitus) [reply app/page.tsx:13]: Leave as home for now

Comment (Radicitus) [reply app/page.tsx:13]: Although it does result in an issue where clicking on the / doesn't scroll all the way to the top.
